services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces:cached
      - devcontainer-cargo-cache:/home/utakata/.cargo/registry
      - devcontainer-npm-cache:/home/utakata/.npm
      - devcontainer-target-cache:/tmp/target
    network_mode: "host"
    environment:
      - CARGO_TARGET_DIR=/tmp/target
      - CARGO_INCREMENTAL=0
      - RUST_BACKTRACE=0
      - VSCODE_IPC_HOOK_CLI=
      - DATABASE_URL=postgres://utakata:password123@localhost:5432/loco_dev
      - POSTGRES_USER=utakata
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=loco_dev
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: utakata
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: loco_dev
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utakata -d loco_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  devcontainer-cargo-cache:
  devcontainer-npm-cache:
  devcontainer-target-cache:
  postgres-data:
