services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspaces:cached
      - devcontainer-cargo-cache:/home/utakata/.cargo/registry
      - devcontainer-npm-cache:/home/utakata/.npm
      - devcontainer-target-cache:/tmp/target
    network_mode: "host"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: sleep infinity

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U utakata -d loco_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  devcontainer-cargo-cache:
  devcontainer-npm-cache:
  devcontainer-target-cache:
  postgres-data:
